config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'kittens#index'

  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: true }, length: { in: 3..20 }
  validates :age, :cuteness, :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json :@kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json :@kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:notice] = 'Kitten created successfully'
      redirect_to root_path(@kitten)
    else
      flash[:alert] = 'Kitten not created, please try again'
      render 'new'
    end
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update(name: params[:kitten][:name], age: params[:kitten][:age])
      flash[:notice] = 'Kitten updated successfully'
      redirect_to kitten_path(@kitten)
    else
      render 'edit'
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
    flash[:notice] = 'Kitten edited successfully'
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    flash[:alert] = 'Your kitten has been deleted'
    redirect_to root_path
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    redirect_to kitten_path(@kitten)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-md-3"></div>
    <div class="col-md-6">

      <%= form_with do |f| %>
        <div class="form-group">
          <%= f.label :name, 'Name: ' %>
          <%= f.text_field :name, autofocus: true, placeholder: "Kitten name" , class: "form-control" %>
        </div><br />
        <div class="form-group">
          <%= f.label :age, 'Age: ' %>
          <%= f.number_field :age, placeholder: "Kitten age" , class: "form-control" %>
        </div><br />
        <div class="form-group">
          <%= f.label :cuteness, 'Cuteness: ' %>
          <%= f.text_field :cuteness, placeholder: "Cuteness" , class: "form-control" %>
        </div><br />
        <div class="form-group">
          <%= f.label :softness, 'Softness: ' %>
          <%= f.text_field :softness, placeholder: "Softeness" , class: "form-control" %>
        </div><br />
        <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

app/views/kittens/edit.html.erb
<h1>Edit new kitty</h1><br />

<%= render 'kittens/form' %>
<%= link_to 'Edit', edit_kitten_path(kitten), method: :DELETE, class: "btn btn-warning" %>

app/views/kittens/index.html.erb
<h1>Hello Kitty!</h1>
<% @kittens.each do |k| %>
  <h2><%= k.name %></h2>
  <h3>Age: <%= k.age %></h3>
  <h3>Cuteness: <%= k.cuteness %></h3>
  <h3>Softness: <%= k.softness %></h3>
  <%= link_to "Delete", kitten, method: :DELETE, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
<% end %>

app/views/kittens/new.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <h1>Add new kitty</h1><br />

    <%= render 'kittens/form' %>
    <%= link_to 'Create', kittens_path, method: :POST, class: "btn btn-success" %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/kittens/show.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <h2>Awesome kitty!</h2>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title border-bottom pb-2"><%= link_to kitten.name, kitten_path(kitten) %> </h5>
        <p class="card-text"><strong>Age: </strong><%= kitten.age %></p>
        <p class="card-text"><strong>Cuteness: </strong><%= kitten.cuteness %></p>
        <p class="card-text"><strong>Softness: </strong><%= kitten.cuteness %></p>
        <%= link_to "Delete", kitten, method: :DELETE, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="<%= root_path%>">Odin Kittens</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <p class="control">
              <%= link_to "All Kittens", kittens_path, class: "nav-link" %>
            </p>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>